[2024-06-05 23:58:01,571][jax._src.xla_bridge][INFO] - Unable to initialize backend 'cuda': 
[2024-06-05 23:58:01,571][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-06-05 23:58:01,572][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2024-06-05 23:58:01,632][__main__][INFO] - Starting Job for Config:
tags: null
project_name: AReLiT-ViZDoom-Two-Colors-Pillar
seed: 1
steps: 100000000
log_interval: 10000
eval_interval: 1000000
eval_episodes: 10
videos: true
record_fps: 30
save_interval: 10000000
save_dir: ./checkpoints/arelit_doom_with_pillar
save_tag: arelit_doom_with_pillar
task:
  task: vizdoom_two_colors
  env_name: doom_with_pillar
  max_episode_steps: 4200
  seed: null
trainer:
  agent: ppo
  seq_model:
    name: arelit
    n_layers: 4
    d_model: 512
    d_head: 64
    d_ffc: 512
    n_heads: 8
    eta: 4
    r: 7
    reset_hidden_on_terminate: true
  env_pool: async
  d_actor: 256
  d_critic: 256
  num_envs: 32
  rollout_len: 200
  sequence_length: 100
  anneal_lr: false
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 8
  update_epochs: 1
  norm_adv: true
  clip_coef: 0.1
  ent_coef:
    initial: 0.003
    final: null
    max_decay_steps: 10000
    power: 1
  vf_coef: 0.5
  max_grad_norm: 4.0
  optimizer:
    learning_rate:
      initial: 0.00025
      final: null
      max_decay_steps: 10000
      power: 1.0
use_wandb: true

[2024-06-05 23:58:01,632][__main__][INFO] - Available Backends:[CpuDevice(id=0)]
[2024-06-05 23:58:06,104][src.trainers.trainers_control][INFO] - Using async env
[2024-06-05 23:58:10,664][src.trainers.trainers_control][INFO] - Observation space: Box(0, 255, (3, 64, 112), uint8)
[2024-06-05 23:58:10,665][src.trainers.trainers_control][INFO] - Action space: Discrete(5)
[2024-06-05 23:58:30,875][src.agents.base_agent][INFO] - Total Number of params: 21761062
[2024-06-05 23:58:30,876][src.agents.base_agent][INFO] - Number of params in Seq Model: 21197696
[2024-06-05 23:58:31,166][absl][WARNING] - Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate by August 1st, 2024.
[2024-06-05 23:58:31,168][absl][INFO] - Skipping global process sync, barrier name: CheckpointManager:create_directory
[2024-06-05 23:58:31,169][absl][INFO] - Found 0 checkpoint steps in /home/jovyan/Egor_C/REPOSITORIES/Memory-RL-Codebase/checkpoints/arelit_doom_with_pillar/arelit_doom_with_pillar
[2024-06-05 23:58:31,170][absl][INFO] - CheckpointManager created, jax.process_index=0, primary_host=0, CheckpointManagerOptions=CheckpointManagerOptions(save_interval_steps=1, max_to_keep=2, keep_time_interval=None, keep_period=None, best_fn=None, best_mode='max', keep_checkpoints_without_metrics=True, step_prefix=None, step_format_fixed_length=None, step_name_format=None, create=True, cleanup_tmp_directories=False, save_on_steps=frozenset(), single_host_load_and_broadcast=False, todelete_subdir=None, enable_background_delete=False, read_only=False, enable_async_checkpointing=True, async_options=AsyncOptions(timeout_secs=None, barrier_sync_fn=None, post_finalization_callback=None), multiprocessing_options=MultiprocessingOptions(primary_host=0, active_processes=None, barrier_sync_key_prefix=None), should_save_fn=None, file_options=FileOptions(path_permission_mode=None)), root_directory=/home/jovyan/Egor_C/REPOSITORIES/Memory-RL-Codebase/checkpoints/arelit_doom_with_pillar/arelit_doom_with_pillar: <orbax.checkpoint.checkpoint_manager.CheckpointManager object at 0x7fc284769d60>
[2024-06-06 00:00:15,548][__main__][INFO] - Seed: 1 Steps: 12800 Metrics: {'step': 12800, 'sps': 193.02560099469574, 'loss': 0.028891314, 'critic_loss': 0.06748229, 'actor_loss': -2.1636562e-05, 'entropy_loss': 1.6093976, 'mean_reward': 0.029863031581044197, 'return_per_episode': 1.2207556, 'is_red': 0.45454545454545453, 'episode_length': 193.63636363636363, 'reward_per_episode': 4.381636363636363}
[2024-06-06 00:00:56,815][__main__][INFO] - Seed: 1 Steps: 25600 Metrics: {'step': 25600, 'sps': 310.3028433347678, 'loss': 0.029949868, 'critic_loss': 0.06957193, 'actor_loss': -8.224697e-06, 'entropy_loss': 1.6092908, 'mean_reward': 0.030726037919521332, 'return_per_episode': 1.249947, 'is_red': 0.5172413793103449, 'episode_length': 199.29310344827587, 'reward_per_episode': 4.606206896551724}
[2024-06-06 00:01:16,855][__main__][INFO] - Seed: 1 Steps: 32000 Metrics: {'step': 32000, 'sps': 319.4649008002086, 'loss': 0.02615465, 'critic_loss': 0.06200691, 'actor_loss': -2.118498e-05, 'entropy_loss': 1.6092064, 'mean_reward': 0.015164018608629704, 'return_per_episode': 1.3649681, 'is_red': 0.46875, 'episode_length': 211.5, 'reward_per_episode': 5.3237499999999995}
[2024-06-06 00:01:25,372][__main__][ERROR] - An exception occurred: Signal SIGINT received. ViZDoom instance has been closed.
Traceback (most recent call last):
  File "/home/jovyan/Egor_C/REPOSITORIES/Memory-RL-Codebase/models/Recurrent_Linear_Transformers/trainer.py", line 82, in main
    loss, metrics, step_count=trainer.step()
  File "/home/jovyan/Egor_C/REPOSITORIES/Memory-RL-Codebase/models/Recurrent_Linear_Transformers/src/trainers/trainers_control.py", line 253, in step
    (loss,(value_loss,entropy_loss,actor_loss,rewards),infos)=self.agent.step(self.random_key)
  File "/home/jovyan/Egor_C/REPOSITORIES/Memory-RL-Codebase/models/Recurrent_Linear_Transformers/src/agents/ppo.py", line 202, in step
    databatch=self.unroll_actors(unroll_key)
  File "/home/jovyan/Egor_C/REPOSITORIES/Memory-RL-Codebase/models/Recurrent_Linear_Transformers/src/agents/base_agent.py", line 156, in unroll_actors
    o_tickplus1,r_tickplus1,term_tickplus1,trunc_tickplus1,info=self.env.step(*jax_to_numpy(acts_tick))
  File "/home/user/conda/envs/memory_rl_relit/lib/python3.9/site-packages/gymnasium/vector/vector_env.py", line 204, in step
    return self.step_wait()
  File "/home/user/conda/envs/memory_rl_relit/lib/python3.9/site-packages/gymnasium/vector/async_vector_env.py", line 333, in step_wait
    self._raise_if_errors(successes)
  File "/home/user/conda/envs/memory_rl_relit/lib/python3.9/site-packages/gymnasium/vector/async_vector_env.py", line 544, in _raise_if_errors
    raise exctype(value)
vizdoom.vizdoom.SignalException: Signal SIGINT received. ViZDoom instance has been closed.
